site_name: SeaJell Documentation
theme:
  name: material
  logo: assets/SeaJell-Logo.png
  favicon: assets/SeaJell-Logo.png
  font:
    text: Josefin Sans
    code: Share Tech Mono
  palette:
    scheme: slate
    primary: orange
    accent: amber
  features:
    - search.highlight
    - search.share
    - header.autohide
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://projects.hanisirfan.xyz/seajell
      name: Website
    - icon: fontawesome/brands/github
      link: https://github.com/hanisirfan/seajell
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://projects.hanisirfan.xyz/seajell
      name: Discord
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/seajelldev
      name: Twitter
copyright: Copyright &copy; 2021 Muhammad Hanis Irfan Bin Mohd Zaid
